### ISSUE TITLE
Collect User Metric for Personas

### ISSUE THREAD

**Issue by jackyhuynh** [jackyhuynh/orange#1]
### Story: **Collect User Metrics for Personas (Working Class and Investors)**

As a **data-driven product manager**, I want to collect **user metrics** for the **working class** and **investor personas** so that we can better understand their behaviors, preferences, and pain points, and enhance our platform to meet their specific needs.

#### **Acceptance Criteria:**

1. **Identify Key Personas:**
   - Define distinct personas for the working class (e.g., salaried employees, freelancers) and investors (e.g., stock market investors, real estate investors).
   
2. **User Metric Collection:**
   - **Demographic Data:** Collect basic demographic information like age, income bracket, education level, employment status (for the working class), and investment portfolios (for investors).
   - **Platform Engagement:** Measure user engagement metrics such as login frequency, feature usage (e.g., investment tracking tools, budgeting tools), and time spent on the platform.
   - **Financial Behavior:** Gather insights into spending habits, savings rates, and financial goals (for working-class users), and investment types, risk tolerance, and portfolio diversity (for investors).
   
3. **Behavioral Patterns:**
   - Analyze differences in user behavior between working class and investor personas, identifying trends like preferred devices, times of usage, or common features accessed.
   - Track any conversion rates (e.g., how often working-class users become investors or engage in more advanced financial tools).
   
4. **Data Segmentation:**
   - Ensure the data is segmented by persona to highlight the distinct needs and behaviors of working-class users and investors, facilitating personalized user journeys.
   
5. **Privacy & Compliance:**
   - Ensure that all data collection is compliant with relevant privacy regulations (e.g., GDPR, CCPA) and that user data is anonymized where necessary.

#### **Measurable Outcomes:**

1. **Increased Engagement:** 
   - Improve engagement among both working-class users and investors by providing personalized recommendations and features tailored to each group’s specific needs.
   
2. **Feature Optimization:**
   - Identify underused features within each persona group and make data-driven adjustments to improve their relevance and usability.
   
3. **Conversion Rate Tracking:** 
   - Track the success rate of converting working-class users into investors by providing easy access to investment education or tools.

**Comment by Salazar2893** [comment]
Story Completed.
