### ISSUE TITLE
Resource Documentation

### ISSUE THREAD

**Issue by jackyhuynh** [jackyhuynh/Orange#5]
## As a Developer:
- I want to see guidelines for the orange project

## So that I can:
- Contribute without blocking others
- Understand about roles, rules, and operations

## Accepting:
- Document is resided on Orange repos
- It is follow the documents writing guidelines

**Comment by jackyhuynh** [comment]
@Salazar2893 Add some docs for Onboarding

**Comment by Salazar2893** [comment]
Closing. Still WIP, will establish a separate project that is specific for knowledge base articles.
