### ISSUE TITLE
investee can register and login

### ISSUE THREAD

**Issue by jackyhuynh** [jackyhuynh/Orange#9]

**Comment by jackyhuynh** [comment]
## Need to break into smaller chunk of #9 Investee can register and login
- Create a Login page
- Some sort of data structure to store a profile (database, or something): SQL Lite (on storage), Post GRE (future state on a seperate container)
- Security the 
- PII information {}? Discuss about this
- Design of front page?
- Need to prevent DDOS (have a methods that verify that is a human is creating an account)
- Key Cloak for user management: https://www.keycloak.org

**Comment by Salazar2893** [comment]
Truc and I created a login page today.
